### ISSUE TITLE
Implement eventRequest

### ISSUE THREAD

**Issue by she-dev** [api-ai/apiai-javascript-client#56]
When I call `client.eventRequest('event_name')` as described in the readme, it's treated as a `textRequest()` and it doesn't trigger the event passed.
I saw that both EventRequest and TextRequest extend Request without adding any changes.

**Comment by ysak-y** [comment]
`textRequest` sends to `/query` endpoint with `query` parameter, and `eventRequest` sends to `/query` endpoint with `event` parameter. 
https://api.ai/docs/reference/agent/query

Only difference point between `textRequest` and `eventRequest` is parameter, this is set as below.
https://github.com/api-ai/apiai-javascript-client/blob/master/es6/ApiAiClient.js#L38
https://github.com/api-ai/apiai-javascript-client/blob/master/es6/ApiAiClient.js#L45

I think below is no problem.
> I saw that both EventRequest and TextRequest extend Request without adding any changes.

So "it doesn't trigger the event passed." is caused by other fact, please tell me response message from request.

**Comment by she-dev** [comment]
I was calling `client.eventRequest('event_name')` without options or event data and the response contained `resolvedQuery: 'event_name'` `action: 'input_unknown'`. I don't have the response right now because I can't reproduce it anymore despite making the same request.

I tried other alternatives, such as triggering events via webhook and got this: 
![intent not found](https://user-images.githubusercontent.com/13964550/29873779-dc88329e-8d94-11e7-9d58-ee39b9c2cbe6.jpeg)
Then I double-checked whether the intent I wanted to trigger had an event with the name of the event I was calling, and that was correct.

I tried triggering the default `WELCOME` event and it was triggered successfully. It seemed to me as if for any reason I wasn't reaching the latest version of my bot definitions in API.ai. Later in the day I was able to trigger my custom event. The only change I remember doing was adding an action to the intent I wanted to trigger but I didn't refer to the action in my code, I just noticed when the intent was triggered I could see the action name in the response.

All in all, it seems that the problem wasn't with the JS client. Thanks for your help.
